### PR TITLE
added isEU in details object

### PR DESCRIPTION
**Pull request by rm-Umar**

### CODE REVIEW

**Review by UmanShahzad — APPROVED** [review]

**Comment by UmanShahzad** [comment]
Will release later.

**Comment by coderholic** [comment]
Changing countries.json is a bad idea. It makes it more likely to introduce a bug/format error, and makes it harder to update. Instead we shuold have counties.json that has all the country codes to names, and eu.json that's just an array of country codes. If a country joins or leaves the EU we just update that file. IIRC this is how we already support currency etc lookups. Definitel needs refactoring into a separate file before we release this!

**Comment by UmanShahzad** [comment]
@coderholic that's a good point we could easily make a mistake there on the initial commit, though in future PRs it's very easy to see what country is being added/removed from the EU because it's 1 country per line now.

One downside with another file is it adds more code, more file loads and more variables versus keeping it in that single `countries` variable and not having to load anymore files or really do much else.

One other benefit of this approach is if we have more metadata on countries in the future that we want in the SDKs directly, it can all get added to this common file. Makes it a lot easier to maintain things long-term with a single file (given that we can edit 1 country per line, which wasn't the case before).

> IIRC this is how we already support currency etc lookups

We don't actually support currency lookups anywhere right now in the SDKs or API. If we did support it, it'd need a `countryCode -> currencyCode` mapping for all country codes, which ends up being a duplicate of countries.json with only different values.

**Comment by coderholic** [comment]
Single file with all metadata makes it harder to add new countries and
changes - because the edit needs to check all attributes instead of just
making the change. I

Id rather have the complexity in well tested loading code that baked into
the schema. Multiple files as simple maps / array seems much better to me
than simpler loading code but complex schema.

Adding new functionality is then a case of adding new simple files, rather
than making a bunch of edits to a single critical file.

And it’s smaller file size too - not a major driver, but a tiny eu.json
will be smaller than a flag on every country, and if we add many more
similar attributes over time it could add up

**Comment by UmanShahzad** [comment]
Alright sure, we'll do it that way.

**Pull request merged**
