### PR TITLE
updated f-strings & removed unnecessary else block.

### PR DESCRIPTION
**Pull request by ProgramR4732**
Made the following changes:

-> replaced format strings to f-strings as it as a much better runtime.
-> removed an unnecessary else block in __getattr__ method.

### CODE REVIEW

**Review by UmanShahzad — COMMENTED** [review]
Better is to put the error case in the condition, e.g. `if attr not in self.details: raise AttributeError`. Then the success case at the end. Reads better.

**Comment by ProgramR4732** [comment]
> Better is to put the error case in the condition, e.g. `if attr not in self.details: raise AttributeError`. Then the success case at the end. Reads better.

Well, that way too seems great to me.

**Comment by ProgramR4732** [comment]
I guess adding __slots__ may also help in saving both runtime & memory.

**Comment by ProgramR4732** [comment]
> Better is to put the error case in the condition, e.g. `if attr not in self.details: raise AttributeError`. Then the success case at the end. Reads better.

Changes made.

**Pull request merged**
