### PR TITLE
ability to read API_URL variable from env too

### PR DESCRIPTION
**Pull request by MFelex**

### CODE REVIEW

**Review by UmanShahzad — COMMENTED** [review]
Why would this ever need to change?

**Comment by MFelex** [comment]
Because of the copyright access issue

**Comment by UmanShahzad** [comment]
What copyright access issue?

**Comment by MFelex** [comment]
The servers on which the application is deployed do not have direct access to the Internet, and we have to use a proxy server and change the address to call  IPinfo.io services.

**Comment by UmanShahzad** [comment]
For proxies, please see https://github.com/ipinfo/python/issues/60

**Pull request closed without merging**
